// ═══════════════════════════════════════════════════════════════════════════════
// TRINITY ID AI OS — Sidecar Manager
// ═══════════════════════════════════════════════════════════════════════════════
//
// FILE:     quest.rs
// PURPOSE:  Quest-aware sidecar coordination for phase-specific model loading
// BIBLE:    Car 4 — IMPLEMENT (ADDIECRAPEYE Orchestrator)
//
// ═══════════════════════════════════════════════════════════════════════════════

//! Quest Board System
//!
//! Quests are JSON files on disk — like contracts on an adventurer's guild wall.
//! The Engineer picks them up, processes them, and writes results.
//!
//! Directory structure:
//!   quests/board/     — Available quests waiting to be claimed
//!   quests/active/    — Currently being worked on
//!   quests/complete/  — Successfully completed with results
//!   quests/failed/    — Failed quests with error logs

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use tracing::{info, warn};

/// Quest status lifecycle
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum QuestStatus {
    Available,
    Claimed,
    Planning,
    InProgress,
    Review,
    Complete,
    Failed,
}

/// Quest type — what kind of work
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum QuestType {
    Bugfix,
    Feature,
    Refactor,
    Documentation,
    Test,
    Analysis,
    CodeGeneration,
    Design,
    Evaluation,
}

/// ADDIE phase this quest belongs to
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AddiePhase {
    Analysis,
    Design,
    Development,
    Implementation,
    Evaluation,
}

/// A quest on the board
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Quest {
    pub id: String,
    pub title: String,
    pub description: String,
    pub quest_type: QuestType,
    pub priority: u8,
    pub addie_phase: AddiePhase,
    pub difficulty_class: u8,
    pub status: QuestStatus,

    /// Files to read for context before starting
    #[serde(default)]
    pub context_files: Vec<String>,

    /// Target files to create or modify
    #[serde(default)]
    pub target_files: Vec<String>,

    /// Shell commands to run for verification
    #[serde(default)]
    pub verify_commands: Vec<String>,

    /// Additional notes
    #[serde(default)]
    pub notes: String,

    /// Plan generated by Opus (filled during planning phase)
    pub plan: Option<serde_json::Value>,

    /// Results of execution
    pub results: Option<QuestResults>,

    /// Execution log entries
    #[serde(default)]
    pub log: Vec<LogEntry>,

    pub created_at: DateTime<Utc>,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
}

/// Results of a completed quest
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestResults {
    pub files_modified: Vec<String>,
    pub files_created: Vec<String>,
    pub verification_output: String,
    pub opus_verdict: String,
    pub xp_earned: u32,
}

/// A single log entry during quest execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogEntry {
    pub timestamp: DateTime<Utc>,
    pub step: String,
    pub model: String,
    pub message: String,
}

/// The quest board — manages quest lifecycle on disk
pub struct QuestBoard {
    pub base_dir: PathBuf,
}

impl QuestBoard {
    pub fn new(base_dir: PathBuf) -> Self {
        Self { base_dir }
    }

    fn board_dir(&self) -> PathBuf {
        self.base_dir.join("board")
    }
    fn active_dir(&self) -> PathBuf {
        self.base_dir.join("active")
    }
    fn complete_dir(&self) -> PathBuf {
        self.base_dir.join("complete")
    }
    fn failed_dir(&self) -> PathBuf {
        self.base_dir.join("failed")
    }

    /// Ensure all directories exist
    pub async fn init(&self) -> anyhow::Result<()> {
        for dir in [
            self.board_dir(),
            self.active_dir(),
            self.complete_dir(),
            self.failed_dir(),
        ] {
            tokio::fs::create_dir_all(&dir).await?;
        }
        Ok(())
    }

    /// List available quests sorted by priority (highest first)
    pub async fn list_available(&self) -> anyhow::Result<Vec<Quest>> {
        let mut quests = self.read_quests_from_dir(&self.board_dir()).await?;
        quests.sort_by(|a, b| a.priority.cmp(&b.priority).reverse());
        Ok(quests)
    }

    /// List active quests
    pub async fn list_active(&self) -> anyhow::Result<Vec<Quest>> {
        self.read_quests_from_dir(&self.active_dir()).await
    }

    /// List completed quests
    pub async fn list_complete(&self) -> anyhow::Result<Vec<Quest>> {
        self.read_quests_from_dir(&self.complete_dir()).await
    }

    /// Claim a quest — move from board to active
    pub async fn claim(&self, quest_id: &str) -> anyhow::Result<Quest> {
        let src = self.board_dir().join(format!("{}.json", quest_id));
        if !src.exists() {
            anyhow::bail!("Quest not found on board: {}", quest_id);
        }

        let mut quest: Quest = self.read_quest(&src).await?;
        quest.status = QuestStatus::Claimed;
        quest.started_at = Some(Utc::now());
        quest.log.push(LogEntry {
            timestamp: Utc::now(),
            step: "claim".to_string(),
            model: "tempo".to_string(),
            message: "Quest claimed by Engineer sidecar".to_string(),
        });

        let dest = self.active_dir().join(format!("{}.json", quest_id));
        self.write_quest(&dest, &quest).await?;
        tokio::fs::remove_file(&src).await?;

        info!("Claimed quest: {} — {}", quest.id, quest.title);
        Ok(quest)
    }

    /// Update an active quest (save progress)
    pub async fn update_active(&self, quest: &Quest) -> anyhow::Result<()> {
        let path = self.active_dir().join(format!("{}.json", quest.id));
        self.write_quest(&path, quest).await
    }

    /// Complete a quest — move from active to complete
    pub async fn complete(&self, quest: &mut Quest, results: QuestResults) -> anyhow::Result<()> {
        quest.status = QuestStatus::Complete;
        quest.completed_at = Some(Utc::now());
        quest.results = Some(results);
        quest.log.push(LogEntry {
            timestamp: Utc::now(),
            step: "complete".to_string(),
            model: "tempo".to_string(),
            message: "Quest completed successfully".to_string(),
        });

        let active_path = self.active_dir().join(format!("{}.json", quest.id));
        let complete_path = self.complete_dir().join(format!("{}.json", quest.id));
        self.write_quest(&complete_path, quest).await?;
        if active_path.exists() {
            tokio::fs::remove_file(&active_path).await?;
        }

        info!("Quest completed: {} — {}", quest.id, quest.title);
        Ok(())
    }

    /// Fail a quest — move from active to failed
    pub async fn fail(&self, quest: &mut Quest, reason: &str) -> anyhow::Result<()> {
        quest.status = QuestStatus::Failed;
        quest.completed_at = Some(Utc::now());
        quest.log.push(LogEntry {
            timestamp: Utc::now(),
            step: "failed".to_string(),
            model: "tempo".to_string(),
            message: format!("Quest failed: {}", reason),
        });

        let active_path = self.active_dir().join(format!("{}.json", quest.id));
        let failed_path = self.failed_dir().join(format!("{}.json", quest.id));
        self.write_quest(&failed_path, quest).await?;
        if active_path.exists() {
            tokio::fs::remove_file(&active_path).await?;
        }

        warn!("Quest failed: {} — {} — {}", quest.id, quest.title, reason);
        Ok(())
    }

    /// Read all quest JSON files from a directory
    async fn read_quests_from_dir(&self, dir: &Path) -> anyhow::Result<Vec<Quest>> {
        let mut quests = Vec::new();
        let mut entries = tokio::fs::read_dir(dir).await?;

        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            if path.extension().map(|e| e == "json").unwrap_or(false) {
                match self.read_quest(&path).await {
                    Ok(q) => quests.push(q),
                    Err(e) => warn!("Failed to read quest {}: {}", path.display(), e),
                }
            }
        }

        Ok(quests)
    }

    async fn read_quest(&self, path: &Path) -> anyhow::Result<Quest> {
        let content = tokio::fs::read_to_string(path).await?;
        Ok(serde_json::from_str(&content)?)
    }

    async fn write_quest(&self, path: &Path, quest: &Quest) -> anyhow::Result<()> {
        let content = serde_json::to_string_pretty(quest)?;
        tokio::fs::write(path, content).await?;
        Ok(())
    }

    /// Run verify commands for a quest
    /// Returns (success, output)
    pub async fn run_verify_commands(
        &self,
        quest: &Quest,
        workspace_root: &Path,
    ) -> (bool, String) {
        if quest.verify_commands.is_empty() {
            return (true, "No verify commands defined".to_string());
        }

        let mut all_output = String::new();
        let mut all_success = true;

        for cmd in &quest.verify_commands {
            info!("Running verify: {}", cmd);

            let output = tokio::process::Command::new("sh")
                .arg("-c")
                .arg(cmd)
                .current_dir(workspace_root)
                .output()
                .await;

            match output {
                Ok(out) => {
                    let stdout = String::from_utf8_lossy(&out.stdout);
                    let stderr = String::from_utf8_lossy(&out.stderr);
                    let success = out.status.success();

                    all_output.push_str(&format!("$ {}\n", cmd));
                    if !stdout.is_empty() {
                        all_output.push_str(&stdout);
                        all_output.push('\n');
                    }
                    if !stderr.is_empty() {
                        all_output.push_str(&stderr);
                        all_output.push('\n');
                    }
                    all_output.push_str(&format!("Exit: {}\n\n", out.status));

                    if !success {
                        all_success = false;
                        all_output.push_str(&format!("❌ Verify failed: {}\n", cmd));
                    } else {
                        all_output.push_str(&format!("✅ Verify passed: {}\n", cmd));
                    }
                }
                Err(e) => {
                    all_success = false;
                    all_output.push_str(&format!("❌ Failed to run '{}': {}\n", cmd, e));
                }
            }
        }

        (all_success, all_output)
    }

    /// Get a single quest by ID from any directory
    pub async fn get_quest(&self, quest_id: &str) -> anyhow::Result<Option<Quest>> {
        // Check board
        let board_path = self.board_dir().join(format!("{}.json", quest_id));
        if board_path.exists() {
            return Ok(Some(self.read_quest(&board_path).await?));
        }

        // Check active
        let active_path = self.active_dir().join(format!("{}.json", quest_id));
        if active_path.exists() {
            return Ok(Some(self.read_quest(&active_path).await?));
        }

        // Check complete
        let complete_path = self.complete_dir().join(format!("{}.json", quest_id));
        if complete_path.exists() {
            return Ok(Some(self.read_quest(&complete_path).await?));
        }

        Ok(None)
    }
}
