/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const handle_command: (a: number, b: number, c: any) => [number, number, number];
export const handle_command_batch: (a: any) => [number, number, number];
export const init_engine: (a: number, b: number) => [number, number];
export const set_event_callback: (a: any) => void;
export const set_init_callback: (a: any) => void;
export const update_scene: (a: number, b: number) => [number, number];
export const wasm_bindgen__closure__destroy__h19c28c7a51ccd65d: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h803e0cbf57792659: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hfe6d060b4a8690b7: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h3772bb38311f9e91: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h80749410d3a7f6ff: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h16086f4e2486ebd9: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0f16ca21869b72a5: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h88b00fe1c6a311eb: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hd7e1ead558a98375: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h81a7aa3a5601115f: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h62909b5096aa33aa: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hdfd59933e0de8bca: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6da439a52ca57c1f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h90df69bd15bd541a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h75208787e0087664: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha79a732d7dbfeecb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h536585999a485636: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h98a7a280c7cfb7ba: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hcfb9558147691898: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6cf682f3b1296ded: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__hd256af75774dece4: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
